/tmp/oracle/hive.log:
    color: green
    label: client
    format: '^(?P<ts>\d{4,4}\-\d{2,2}\-\d{2,2}\s+\d{2,2}:\d{2,2}:\d{2,2},\d{3})\s+(?P<level>\w+)\s+\[(?P<id>[^\]]+)\]:\s+(?P<text>.*)'
hive-metastore:
    format: '^(?P<ts>\d{4,4}\-\d{2,2}\-\d{2,2}\s+\d{2,2}:\d{2,2}:\d{2,2},\d{3})\s+(?P<level>\w+)\s+\[(?P<id>[^\]]+)\]:\s+(?P<text>.*)'
    label: metastore
    color: yellow
hive-server:
    format: '^(?P<ts>\d{4,4}\-\d{2,2}\-\d{2,2}\s+\d{2,2}:\d{2,2}:\d{2,2},\d{3})\s+(?P<level>\w+)\s+\[(?P<id>[^\]]+)\]:\s+(?P<text>.*)'
    label: server
    color: blue
WARNING:
    color: yellow
ERROR:
    color: red
INFO:
    color: blue
